const products = [
  {
    name: "Crispy Fried Mushroom Burger",
    price: 18,
    image: "",
    serving: 342,
    category: "main dish",
    nutrition: {
      calories: 668,
      protein: 45,
      carbs: 52,
      fats: 30,
    },
    description:
      "Indulge in the rich umami flavors of our Crispy Mushroom Burger, where savory mushrooms are expertly seasoned and crisped to perfection. Nestled within a soft bun, this burger offers a delightful combination of textures and earthy notes.",
    available: true,
  },
  {
    name: "Million Dollar Chicken Casserole",
    price: 35,
    image: "",
    serving: 500,
    category: "main dish",
    nutrition: {
      calories: 890,
      protein: 52,
      carbs: 67,
      fats: 34,
    },
    description:
      "Elevate your dining experience with our Million Dollar Chicken Casserole. Succulent chicken pieces are bathed in a luxurious creamy sauce, topped with a golden layer of cheese and crispy breadcrumbs. A comforting and decadent dish that lives up to its name.",
    available: true,
  },
  {
    name: "Cast Iron Steak",
    price: 42,
    image: "",
    serving: 320,
    category: "main dish",
    nutrition: {
      calories: 389,
      protein: 52,
      carbs: 12,
      fats: 31,
    },
    description:
      "Savor the bold and robust taste of our Cast Iron Steak. Cooked to your preference, this premium cut is seared in a cast iron pan to lock in juices and create a mouthwatering crust. Each bite delivers a perfect balance of tenderness and flavor.",
    available: true,
  },
  {
    name: "BBQ Country Style Ribs",
    price: 48,
    image: "",
    serving: 600,
    category: "main dish",
    nutrition: {
      calories: 1278,
      protein: 72,
      carbs: 30,
      fats: 54,
    },
    description:
      "Dive into a feast of BBQ Country Style Ribs, where tender pork ribs are slow-cooked to perfection and generously glazed with our signature barbecue sauce. The result is a harmonious blend of smoky, sweet, and savory flavors that will leave your taste buds dancing.",
    available: true,
  },
  {
    name: "Instant Pot Pulled Pork",
    price: 34,
    image: "",
    serving: 415,
    category: "main dish",
    nutrition: {
      calories: 845,
      protein: 65,
      carbs: 37,
      fats: 26,
    },
    description:
      "Experience the convenience and flavor explosion of our Instant Pot Pulled Pork. Slow-cooked for hours, the succulent pork is expertly shredded and infused with a smoky barbecue essence. Perfectly tender, this dish is a go-to for those who appreciate quick yet delicious meals.",
    available: true,
  },
  {
    name: "Philly Cheesesteak",
    price: 29,
    image: "",
    serving: 430,
    category: "main dish",
    nutrition: {
      calories: 678,
      protein: 48,
      carbs: 30,
      fats: 29,
    },
    description:
      "Transport your taste buds to Philadelphia with our iconic Philly Cheesesteak. Thinly sliced beefsteak meets sautéed onions and melted cheese, all nestled in a soft roll. A classic combination that captures the essence of this beloved sandwich.",
    available: true,
  },
  {
    name: "Louisiana Creole Gumbo",
    price: 72,
    image: "",
    serving: 540,
    category: "main dish",
    nutrition: {
      calories: 890,
      protein: 67,
      carbs: 34,
      fats: 39,
    },
    description:
      "Take a culinary journey to the heart of Louisiana with our Creole Gumbo. A soul-warming stew featuring a medley of seafood or meats, aromatic spices, and the holy trinity of Cajun cuisine—bell peppers, onions, and celery. A true taste of the Bayou.",
    available: true,
  },
  {
    name: "Juicy Beef and Bacon Burgers",
    price: 89,
    image: "",
    serving: 700,
    category: "main dish",
    nutrition: {
      calories: 1344,
      protein: 89,
      carbs: 45,
      fats: 62,
    },
    description:
      "Sink your teeth into our Juicy Beef and Bacon Burgers, where premium ground beef meets crispy bacon to create a flavor-packed patty. Grilled to perfection, these burgers are a carnivore's delight, offering a burst of smoky and savory goodness in every bite.",
    available: true,
  },
  {
    name: "Pastrami Burgers",
    price: 79,
    image: "",
    serving: 650,
    category: "main dish",
    nutrition: {
      calories: 934,
      protein: 55,
      carbs: 43,
      fats: 49,
    },
    description:
      "Experience a twist on the classic burger with our Pastrami Burgers. Succulent ground beef is complemented by layers of thinly sliced pastrami, creating a delightful combination of textures and flavors. A hearty choice for those craving a unique and satisfying meal.",
    available: true,
  },
  {
    name: "Grilled Beef and Turkey Burgers With Basil",
    price: 56,
    image: "",
    serving: 678,
    category: "main dish",
    nutrition: {
      calories: 1400,
      protein: 90,
      carbs: 34,
      fats: 29,
    },
    description:
      "Delight in the freshness of our Grilled Beef and Turkey Burgers infused with aromatic basil. The lean turkey complements the richness of the beef, while the herbal notes add a refreshing twist. A healthier option without compromising on flavor.",
    available: true,
  },
  {
    name: "Air Fryer Mac and Cheese Balls",
    price: 18,
    image: "",
    serving: 285,
    category: "appetizer",
    nutrition: {
      calories: 367,
      protein: 20,
      carbs: 19,
      fats: 34,
    },
    description:
      "Bite into the golden perfection of our Air Fryer Mac and Cheese Balls, where creamy macaroni and cheese is molded into bite-sized orbs and air-fried to a crispy exterior. The result is a delightful blend of cheesy goodness encased in a crunchy shell.",
    available: true,
  },
  {
    name: "Fried Pickles Recipe",
    price: 21,
    image: "",
    serving: 320,
    category: "appetizer",
    nutrition: {
      calories: 248,
      protein: 2,
      carbs: 13,
      fats: 5,
    },
    description:
      "Elevate your snacking experience with our Fried Pickles—crisp dill pickle spears coated in a seasoned batter and deep-fried to a golden hue. Served with a zesty dipping sauce, these tangy delights are the perfect balance of crunch and flavor.",
    available: true,
  },
  {
    name: "Classic Deviled Eggs",
    price: 27,
    image: "",
    serving: 380,
    category: "appetizer",
    nutrition: {
      calories: 423,
      protein: 28,
      carbs: 18,
      fats: 8,
    },
    description:
      "Experience the timeless appeal of our Classic Deviled Eggs, where hard-boiled eggs are halved and filled with a velvety, seasoned yolk mixture. Garnished with a sprinkle of paprika, these appetizers are a nostalgic and savory start to any meal.",
    available: true,
  },
  {
    name: "Chili Cheese Fries",
    price: 35,
    image: "",
    serving: 480,
    category: "appetizer",
    nutrition: {
      calories: 542,
      protein: 20,
      carbs: 56,
      fats: 34,
    },
    description:
      "Indulge in the ultimate comfort food with our Chili Cheese Fries—crispy fries smothered in savory chili and melted cheese. Each forkful delivers a satisfying combination of textures and bold flavors that will leave your taste buds craving more.",
    available: true,
  },
  {
    name: "Candied Bacon Cracker Bites",
    price: 38,
    image: "",
    serving: 400,
    category: "appetizer",
    nutrition: {
      calories: 543,
      protein: 38,
      carbs: 23,
      fats: 30,
    },
    description:
      "Delight in the sweet and savory harmony of our Candied Bacon Cracker Bites. Crispy bacon strips are candied to perfection, then paired with buttery crackers for a delectable bite-sized treat that strikes the perfect balance between indulgence and sophistication.",
    available: true,
  },
  {
    name: "Crispy Garlic-Parmesan Wings",
    price: 42,
    image: "",
    serving: 300,
    category: "appetizer",
    nutrition: {
      calories: 612,
      protein: 39,
      carbs: 12,
      fats: 25,
    },
    description:
      "Tantalize your taste buds with our Crispy Garlic-Parmesan Wings, where succulent chicken wings are coated in a crispy garlic-parmesan crust. Each wing is a flavor explosion, combining the richness of parmesan with the aromatic allure of garlic for an unforgettable appetizer experience.",
    available: true,
  },
  {
    name: "Air Fryer Bloomin' Onion",
    price: 22,
    image: "",
    serving: 312,
    category: "appetizer",
    nutrition: {
      calories: 388,
      protein: 5,
      carbs: 23,
      fats: 18,
    },
    description:
      "Embark on a culinary adventure with our Air Fryer Bloomin' Onion Recipe. Sliced onions are seasoned, coated, and air-fried to create a blooming masterpiece. Served with a tangy dipping sauce, this appetizer is a delightful twist on a classic favorite, minus the deep-frying guilt.",
    available: true,
  },
  {
    name: "Appalachian Apple Stack Cake",
    price: 36,
    image: "",
    serving: 250,
    category: "dessert",
    nutrition: {
      calories: 456,
      protein: 1,
      carbs: 45,
      fats: 34,
    },
    description:
      "Immerse yourself in the rich tradition of the Appalachian Apple Stack Cake. Layer upon layer of spiced apple filling is nestled between thin, molasses-infused cake rounds. The result is a nostalgic and heartwarming dessert that pays homage to the culinary heritage of the Appalachian region.",
    available: true,
  },
  {
    name: "Fresh Peach Crumble",
    price: 24,
    image: "",
    serving: 180,
    category: "dessert",
    nutrition: {
      calories: 234,
      protein: 2,
      carbs: 28,
      fats: 17,
    },
    description:
      "Indulge in the essence of summer with our Fresh Peach Crumble. Juicy, ripe peaches are bathed in cinnamon and sugar, then crowned with a buttery crumbly topping. Served warm and paired with a scoop of vanilla ice cream, this dessert is a celebration of seasonal sweetness.",
    available: true,
  },
  {
    name: "Blackberry Cobbler",
    price: 31,
    image: "",
    serving: 312,
    category: "dessert",
    nutrition: {
      calories: 345,
      protein: 4,
      carbs: 56,
      fats: 30,
    },
    description:
      "Delight in the rustic charm of our Blackberry Cobbler, where plump blackberries bubble beneath a golden lattice crust. The perfect marriage of tart and sweet, this timeless dessert captures the essence of home-baked goodness with each spoonful.",
    available: true,
  },
  {
    name: "Fresh Strawberry Pie",
    price: 23,
    image: "",
    serving: 310,
    category: "dessert",
    nutrition: {
      calories: 512,
      protein: 8,
      carbs: 38,
      fats: 25,
    },
    description:
      "Experience the vibrant flavors of the season with our Fresh Strawberry Pie. Succulent strawberries, bathed in a glossy glaze, rest atop a buttery pie crust. Each slice is a symphony of textures and tastes, offering a burst of freshness in every bite.",
    available: true,
  },
  {
    name: "Butterscotch Cookies",
    price: 16,
    image: "",
    serving: 286,
    category: "dessert",
    nutrition: {
      calories: 314,
      protein: 5,
      carbs: 52,
      fats: 21,
    },
    description:
      "Succumb to the allure of our Butterscotch Cookies—soft, chewy delights infused with the rich, buttery goodness of butterscotch. Baked to perfection, these cookies strike a perfect balance between sweet and savory, making them an irresistible treat for any dessert enthusiast.",
    available: true,
  },
  {
    name: "Whiskey Cake With Brown Butter Whiskey Glaze",
    price: 43,
    image: "",
    serving: 560,
    category: "dessert",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description:
      "Embark on a journey of indulgence with our Whiskey Cake adorned in a decadent Brown Butter Whiskey Glaze. Each moist and flavorful slice is infused with the nuanced notes of whiskey, creating a harmonious symphony of richness. A dessert that invites you to savor every luxurious moment.",
    available: true,
  },
  {
    name: "Lava Flow Hawaiian Tropical Drink",
    price: 11,
    image: "",
    serving: 200,
    category: "beverage",
    nutrition: {
      calories: 245,
      protein: 0,
      carbs: 15,
      fats: 5,
    },
    description:
      "Transport yourself to a tropical paradise with our Lava Flow Hawaiian Tropical Drink. A mesmerizing blend of coconut cream, fresh pineapple juice, and ripe strawberries creates vibrant layers reminiscent of flowing lava. Served over ice, this refreshing beverage is a taste of the exotic islands in every sip.",
    available: true,
  },
  {
    name: "Lime Cola",
    price: 8,
    image: "",
    serving: 300,
    category: "beverage",
    nutrition: {
      calories: 189,
      protein: 0,
      carbs: 29,
      fats: 6,
    },
    description:
      "Quench your thirst with the zesty twist of our Lime Cola. Classic cola meets the bright and tangy essence of freshly squeezed limes, creating a revitalizing beverage that strikes the perfect balance between sweetness and citrusy refreshment. An effervescent delight for lime lovers.",
    available: true,
  },
  {
    name: "Sweet Sunrise Drink",
    price: 19,
    image: "",
    serving: 290,
    category: "beverage",
    nutrition: {
      calories: 312,
      protein: 0,
      carbs: 22,
      fats: 12,
    },
    description:
      "Embrace the beauty of a new day with our Sweet Sunrise Drink. A medley of tropical fruits, including orange and pineapple, creates a colorful sunrise-inspired blend. Garnished with a slice of citrus and served in a chilled glass, this beverage is a sweet and uplifting way to start any meal.",
    available: true,
  },
  {
    name: "Death by Chocolate Cocktail",
    price: 25,
    image: "",
    serving: 350,
    category: "beverage",
    nutrition: {
      calories: 734,
      protein: 8,
      carbs: 75,
      fats: 40,
    },
    description:
      "Indulge in the decadence of our Death by Chocolate Cocktail, a sinfully rich concoction for chocolate enthusiasts. A blend of premium dark chocolate liqueur, creamy Irish cream, and a hint of coffee liqueur creates a luxurious, dessert-like drink. Sipped slowly, this cocktail is a heavenly treat for those with a sweet tooth and a passion for all things chocolate.",
    available: true,
  },
  {
    name: "",
    price: 43,
    image: "",
    serving: 560,
    category: "side",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description: "",
    available: true,
  },
  {
    name: "",
    price: 43,
    image: "",
    serving: 560,
    category: "side",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description: "",
    available: true,
  },
  {
    name: "",
    price: 43,
    image: "",
    serving: 560,
    category: "side",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description: "",
    available: true,
  },
  {
    name: "",
    price: 43,
    image: "",
    serving: 560,
    category: "side",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description: "",
    available: true,
  },
  {
    name: "",
    price: 43,
    image: "",
    serving: 560,
    category: "side",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description: "",
    available: true,
  },
  {
    name: "",
    price: 43,
    image: "",
    serving: 560,
    category: "side",
    nutrition: {
      calories: 1028,
      protein: 11,
      carbs: 67,
      fats: 32,
    },
    description: "",
    available: true,
  },
];
